__title__ = 'Flask-flaat'
__description__ = 'User session management with tokens for Flask'
__url__ = 'https://github.com/BorjaEst/flask-flaat'
__version_info__ = ('0', '0', '2')
__version__ = '.'.join(__version_info__)
__author__ = 'Borja Esteban'
__author_email__ = ''
__maintainer__ = 'BorjaEst'
__license__ = 'MIT'
__copyright__ = '(c) 2022 by Borja Esteban'
